// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type AddressBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address: string;
};

export type Cookie = {
    Domain: string;
    Expires: string;
    HttpOnly: boolean;
    MaxAge: number;
    Name: string;
    Partitioned: boolean;
    Path: string;
    Quoted: boolean;
    Raw: string;
    RawExpires: string;
    SameSite: number;
    Secure: boolean;
    Unparsed: Array<string> | null;
    Value: string;
};

export type CreateProjectInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type JoinCodeBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address: string;
    code: string;
};

export type LoginInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    password: string;
    username: string;
};

export type ProjectView = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created_at: string;
    id: string;
    name: string;
};

export type RegisterInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    password: string;
    username: string;
};

export type UserView = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    id: number;
    username: string;
};

export type AddressBodyWritable = {
    address: string;
};

export type CreateProjectInputBodyWritable = {
    name: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type JoinCodeBodyWritable = {
    address: string;
    code: string;
};

export type LoginInputBodyWritable = {
    password: string;
    username: string;
};

export type ProjectViewWritable = {
    created_at: string;
    id: string;
    name: string;
};

export type RegisterInputBodyWritable = {
    email: string;
    password: string;
    username: string;
};

export type UserViewWritable = {
    email: string;
    id: number;
    username: string;
};

export type LoginData = {
    body: LoginInputBodyWritable;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: UserView;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * OK
     */
    200: UserView;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RegisterData = {
    body: RegisterInputBodyWritable;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * OK
     */
    200: UserView;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ListProjectsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListProjectsError = ListProjectsErrors[keyof ListProjectsErrors];

export type ListProjectsResponses = {
    /**
     * OK
     */
    200: Array<ProjectView> | null;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: CreateProjectInputBodyWritable;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * OK
     */
    200: ProjectView;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type DeleteProjectErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type GetProjectErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * OK
     */
    200: ProjectView;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type ProjectAddressData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/address';
};

export type ProjectAddressErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ProjectAddressError = ProjectAddressErrors[keyof ProjectAddressErrors];

export type ProjectAddressResponses = {
    /**
     * OK
     */
    200: AddressBody;
};

export type ProjectAddressResponse = ProjectAddressResponses[keyof ProjectAddressResponses];

export type ProjectJoinCodeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/join-code';
};

export type ProjectJoinCodeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ProjectJoinCodeError = ProjectJoinCodeErrors[keyof ProjectJoinCodeErrors];

export type ProjectJoinCodeResponses = {
    /**
     * OK
     */
    200: JoinCodeBody;
};

export type ProjectJoinCodeResponse = ProjectJoinCodeResponses[keyof ProjectJoinCodeResponses];
